# Automatically merge Dependabot PRs when version comparison is within the range
# that is configured in .github/auto-merge.yml
name: Auto-Merge Dependabot PRs
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Auto-merge Dependabot PRs
        uses: iobroker-bot-orga/action-automerge-dependabot@main
        with:
          github-token: ${{ secrets.AUTO_MERGE_TOKEN }}
          
